version: '3.8'

services:
  web:
    build: .
    container_name: valsci-web
    ports:
      - "3000:3000"
    environment:
      - FLASK_APP=run.py
    volumes:
      - ./app/config/env_vars.json:/valsci/app/config/env_vars.json
      - semantic_scholar_data:/valsci/semantic_scholar/datasets
      - queued_jobs:/valsci/queued_jobs
      - saved_jobs:/valsci/saved_jobs
    restart: unless-stopped

  processor:
    build: .
    container_name: valsci-processor
    command: python processor.py
    volumes:
      - ./app/config/env_vars.json:/valsci/app/config/env_vars.json
      - semantic_scholar_data:/valsci/semantic_scholar/datasets
      - queued_jobs:/valsci/queued_jobs
      - saved_jobs:/valsci/saved_jobs
    restart: unless-stopped
    depends_on:
      - web

volumes:
  semantic_scholar_data:
  queued_jobs:
  saved_jobs: